name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        make install
    - name: Test with pytest
      run: |
        make test
        
[![Actions Status](https://github.com/sgriesmer/azure-pipeline/workflows/Python%20application%20test%20with%20Github%20Actions/badge.svg)](https://github.com/sgriesmer/azure-pipeline/actions)
